#!/usr/bin/env python3
import sys
import asyncio
import nats
import json
from pathlib import Path

# NATS Broker
BROKER = 'nats://resilmesh-ap-nats:4222'

# NATS topic
TOPIC = 'alerts'

async def main():
    # Get alert as JSON
    alert = json.loads(Path(sys.argv[1]).read_text())

    # Forward alert to NATS
    nc = await nats.connect(servers=[BROKER])
    await nc.publish(TOPIC, json.dumps(alert).encode('utf-8'))
    await nc.flush()
    await nc.close()

if __name__ == '__main__':
    asyncio.run(main())
