#+TITLE: Wazuh

* Wazuh

This project contains all necessary resources to build and deploy Wazuh on the
ResilMesh network.

** Wazuh server

The server component will be tasked with receiving incoming logs from Wazuh
agents and other sources, in order to analyze them and send the necessary alerts
to the NATS broker.

Before deployment, the manager needs to generate and update several
configuration files.  The following sections describe the steps necessary to
prepare the Wazuh manager.  Unless otherwise mentioned, all references to ~$dir~
in this section will refer to the top level =server/= folder within this
repository, as an absolute path.

*** COMMENT Variables

#+NAME: wazuh-server-directory
#+begin_src emacs-lisp :cache yes
  (concat default-directory "server/")
#+end_src

*** Generating server certificates

The first step is generating a set of valid certificates using the
=generate-indexer-certs.yaml= Compose file, as described by the [[https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html][Wazuh
documentation]].

#+NAME: wazuh-server-generate-certificates
#+begin_src sh :var dir=wazuh-server-directory() :results verbatim
  cd $dir

  if [ ! -d config ]; then
      cp -r base-configuration config
  fi
  docker compose -f docker-compose-certs.yaml up 2>&1
  # Remove lingering container
  docker compose -f docker-compose-certs.yaml down --remove-orphans 2>&1
#+end_src

This step creates a =config/= directory.  It might be useful to delete the
directory first if attempting to recreate the manager configuration from
scratch.  However, do note that administrator privileges might be needed to
fully delete the folder as it might contain files generated by Wazuh.

#+NAME: wazuh-server-remove-config-directory
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :var dir=wazuh-server-directory() :results silent
  cd $dir

  if [ -d config ]; then
      rm -r config
  fi
#+end_src

**** Generating server configuration files

The next step is to run Wazuh using the =docker-compose-original.yaml= Compose
file, in order to generate all the config files.  This Wazuh instance will not
be needed further, so it should be taken down afterwards.

#+NAME: wazuh-server-run-vanilla
#+CALL: docker-compose-run(dir=wazuh-server-directory(), file="docker-compose-original.yaml")

#+NAME: wazuh-server-kill-vanilla
#+CALL: docker-compose-kill(dir=wazuh-server-directory(), file="docker-compose-original.yaml")

**** Updating server configuration files

Afterwards, the generated configuration files have to be updated with new ones
wherever necessary.  Administrator privileges are likely to be needed for this.

#+NAME: wazuh-server-update-configuration-files
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :var dir=wazuh-server-directory() :results silent
  cd $dir

  mkdir -p config/wazuh_etc/rules
  cp -t config/wazuh_etc/rules rules/*
  mkdir -p config/wazuh_etc/decoders
  cp -t config/wazuh_etc/decoders decoders/*
  mkdir -p config/wazuh_integrations
  cp -t config/wazuh_integrations integrations/*
  mkdir -p config/wazuh_cluster
  cp ossec.conf config/wazuh_cluster/wazuh_manager.conf
#+end_src

**** Running the server

To run the server, simply deploy it using ~docker compose~.

#+NAME: wazuh-server-run
#+CALL: docker-compose-run(dir=wazuh-server-directory())

#+NAME: wazuh-server-kill
#+CALL: docker-compose-kill(dir=wazuh-server-directory())

*** COMMENT Shortcuts

- *Recreate everything*

  #+CALL: wazuh-server-generate-certificates()

  #+CALL: wazuh-server-run-vanilla()

  #+CALL: wazuh-server-kill-vanilla()

  [[wazuh-server-update-configuration-files][wazuh-server-update-configuration-files()]]

  #+CALL: wazuh-server-run()

  #+CALL: wazuh-server-kill()

- *Remove and cleanup*

  #+CALL: wazuh-server-kill-vanilla()

  #+CALL: wazuh-server-kill()

  [[wazuh-server-remove-config-directory][wazuh-server-remove-config-directory()]]

** Wazuh agent

The agent component is to be deployed on devices within the network, in order to
monitor device behavior and report back to the Wazuh server.  This repository
offers an example container running Ubuntu 22.04.

Unless otherwise mentioned, all references to ~$dir~ in this section will refer
to the top level =agent/= folder within this repository, as an absolute path.

*** COMMENT Variables

#+NAME: wazuh-agent-directory
#+begin_src emacs-lisp :cache yes
  (concat default-directory "agent/")
#+end_src

*** Deployment

**** Running the agent

To run the agent, simply deploy it using ~docker compose~.

#+NAME: wazuh-agent-run
#+CALL: docker-compose-run(dir=wazuh-agent-directory())

#+NAME: wazuh-agent-kill
#+CALL: docker-compose-kill(dir=wazuh-agent-directory())

** Deployment

After initialization, all components can be deployed through the top level
=docker-compose.yaml= file.

#+begin_src sh
  docker compose up -d
#+end_src

#+CALL: docker-compose-run()

#+CALL: docker-compose-kill()

** COMMENT Common code blocks

#+NAME: current-directory
#+begin_src emacs-lisp
  default-directory
#+end_src

#+NAME: docker-compose-run
#+begin_src sh :var dir=current-directory() :var file="docker-compose.yaml" :results verbatim
  cd $dir

  docker compose -f $file up --build -d 2>&1
#+end_src

#+NAME: docker-compose-kill
#+begin_src sh :var dir=current-directory() :var file="docker-compose.yaml" :results verbatim
  cd $dir

  docker compose -f $file down --remove-orphans 2>&1
#+end_src
