#+TITLE: Wazuh

This project contains all necessary resources to build and deploy Wazuh on the
ResilMesh network.


* Custom content

In order to modify the Wazuh server's configuration files (rules, decoders,
etc), a series of files/directories inside the =server/= directory are
provided - please modify them according to your needs.  The different
configuration files/directories are:

- =rules/= :: Add any custom rule files here.

- =decoders/= :: Add any custom decoders here.

- =integrations/= :: Add any custom integrations here.

- =ossec.conf= :: This file will replace the server's =ossec.conf= file, edit it
  according to your needs.

* Deployment

Before deployment, the manager needs to generate and update several
configuration files.  The following sections describe the steps necessary to
prepare the Wazuh manager.  Unless otherwise mentioned, all references to ~$dir~
in this section will refer to the absolute path of the top level =server/=
folder within this repository.

** Generating server certificates

The first step is generating a set of valid certificates using the
=generate-indexer-certs.yaml= Compose file, as described by the [[https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html][Wazuh
documentation]].

#+NAME: wazuh-server-generate-certificates
#+begin_src sh :var dir=wazuh-server-directory() :results verbatim
  cd $dir

  if [ ! -d config ]; then
      cp -r base-configuration config
  fi
  docker compose -f docker-compose-certs.yaml up
  # Remove lingering container
  docker compose -f docker-compose-certs.yaml down --remove-orphans
#+end_src

This step creates a =config/= directory.  It might be useful to delete the
directory first if attempting to recreate the manager configuration from
scratch.  However, do note that administrator privileges might be needed to
fully delete the folder as it might contain files generated by Wazuh.

#+NAME: wazuh-server-remove-config-directory
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :var dir=wazuh-server-directory() :results silent
  cd $dir

  if [ -d config ]; then
      rm -r config
  fi
#+end_src

** Generating server configuration files

The next step is to run Wazuh using the =docker-compose-original.yaml= Compose
file, in order to generate all the config files.  This Wazuh instance will not
be needed further, so it should be taken down afterwards.  If you're using v1 of
Docker Compose, make sure to replace ~docker compose~ with ~docker-compose~.

#+NAME: wazuh-run-original
#+begin_src sh :var dir=wazuh-server-directory()
  cd $dir
  docker compose --file docker-compose-original.yaml up -d
#+end_src

#+NAME: wazuh-kill-original
#+begin_src sh :var dir=wazuh-server-directory()
  cd $dir
  docker compose --file docker-compose-original.yaml down --remove-orphans
#+end_src

** Updating server configuration files

Afterwards, the generated configuration files have to be updated with new ones
wherever necessary.  Administrator privileges are likely to be needed for this.

#+NAME: wazuh-server-update-configuration-files
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :var dir=wazuh-server-directory() :results silent
  cd $dir

  mkdir -p config/wazuh_etc/rules
  cp -t config/wazuh_etc/rules rules/*
  mkdir -p config/wazuh_etc/decoders
  cp -t config/wazuh_etc/decoders decoders/*
  mkdir -p config/wazuh_integrations
  cp -t config/wazuh_integrations integrations/*
  mkdir -p config/wazuh_cluster

  chmod --reference=config/wazuh_etc/rules/local_rules.xml ./config/wazuh_etc/rules/*

  chgrp -R systemd-journal config/wazuh_integrations config/wazuh_etc/rules config/wazuh_etc/decoders
  chmod 770 config/wazuh_etc/decoders/* config/wazuh_integrations config/wazuh_etc/rules/*
  chmod 750 config/wazuh_integrations/*
#+end_src

Make sure that permissions are set appropriately for all copied files.  Files
under =rules/= and =integrations/= must belong to the =systemd-journal= group
and have =750= permissions.

** Creating the ResilMesh network

All ResilMesh containers run on a special network called =resilmesh_network=.
This network should be created in advance with the ~docker network create~
command:

#+begin_src sh
  docker network create resilmesh_network
#+end_src

** Setting environment variables

The project includes an =.env.example= file with information regarding the
available environment variables.  Make a copy of the file, rename it to =.env=,
and fill/modify any necessary values.

** Launching Wazuh

After initialization, all components can be deployed through the top level
=docker-compose.yaml= file.  If you're using v1 of Docker Compose, make sure to
replace ~docker compose~ with ~docker-compose~.

#+NAME: wazuh-run
#+begin_src sh :var dir=wazuh-server-directory() :results verbatim
  docker compose -f docker-compose.yaml up --build -d
#+end_src

#+NAME: wazuh-stop
#+begin_src sh :var dir=wazuh-server-directory()
  docker compose -f docker-compose.yaml down --remove-orphans
#+end_src

* Code blocks

** Variables

#+NAME: current-directory
#+begin_src emacs-lisp
  default-directory
#+end_src

#+NAME: wazuh-agent-directory
#+begin_src emacs-lisp :cache yes
  (concat default-directory "agent/")
#+end_src

#+NAME: wazuh-server-directory
#+begin_src emacs-lisp :cache yes
  (concat default-directory "server/")
#+end_src

** Manager reconfiguration

[[wazuh-server-remove-config-directory][wazuh-server-remove-config-directory()]]

#+CALL: wazuh-server-generate-certificates()

#+CALL: wazuh-server-run-vanilla()

#+CALL: wazuh-server-kill-vanilla()

[[wazuh-server-update-configuration-files][wazuh-server-update-configuration-files()]]
