#+TITLE: Wazuh

This project contains all necessary resources to build and deploy Wazuh on the
ResilMesh network.

* Deployment

Before deployment, the manager needs to generate and update several
configuration files.  The following sections describe the steps necessary to
prepare the Wazuh manager.  Unless otherwise mentioned, all references to ~$dir~
in this section will refer to the absolute path of the top level =server/=
folder within this repository.

** Generating server certificates

The first step is generating a set of valid certificates using the
=generate-indexer-certs.yaml= Compose file, as described by the [[https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html][Wazuh
documentation]].

#+NAME: wazuh-server-generate-certificates
#+begin_src sh :var dir=wazuh-server-directory() :results verbatim
  cd $dir

  if [ ! -d config ]; then
      cp -r base-configuration config
  fi
  docker compose -f docker-compose-certs.yaml up
  # Remove lingering container
  docker compose -f docker-compose-certs.yaml down --remove-orphans
#+end_src

This step creates a =config/= directory.  It might be useful to delete the
directory first if attempting to recreate the manager configuration from
scratch.  However, do note that administrator privileges might be needed to
fully delete the folder as it might contain files generated by Wazuh.

#+NAME: wazuh-server-remove-config-directory
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :var dir=wazuh-server-directory() :results silent
  cd $dir

  if [ -d config ]; then
      rm -r config
  fi
#+end_src

** Generating server configuration files

The next step is to run Wazuh using the =docker-compose-original.yaml= Compose
file, in order to generate all the config files.  This Wazuh instance will not
be needed further, so it should be taken down afterwards.

#+NAME: wazuh-server-run-vanilla
#+CALL: docker-compose-run(dir=wazuh-server-directory(), file="docker-compose-original.yaml")

#+NAME: wazuh-server-kill-vanilla
#+CALL: docker-compose-kill(dir=wazuh-server-directory(), file="docker-compose-original.yaml")

** Updating server configuration files

Afterwards, the generated configuration files have to be updated with new ones
wherever necessary.  Administrator privileges are likely to be needed for this.

#+NAME: wazuh-server-update-configuration-files
#+begin_src sh :dir (concat "/sudo::" (expand-file-name ".")) :var dir=wazuh-server-directory() :results silent
  cd $dir

  mkdir -p config/wazuh_etc/rules
  cp -t config/wazuh_etc/rules rules/*
  mkdir -p config/wazuh_etc/decoders
  cp -t config/wazuh_etc/decoders decoders/*
  mkdir -p config/wazuh_integrations
  cp -t config/wazuh_integrations integrations/*
  mkdir -p config/wazuh_cluster
#+end_src

** Creating the ResilMesh network

All ResilMesh containers run on a special network called =resilmesh_network=.
This network should be created in advance with the ~docker network create~
command.  There are several static IPs in use by the project that are dependent
on the ResilMesh network, so please ensure that the subnet they belong to
matches the one used by the network.  The default configuration assumes the
subnet =192.168.200.0/24=.  A network using this subnet can be created using the
following command.

#+begin_src sh
  docker network create --subnet 192.168.200.0/24 --gateway=192.168.200.1 resilmesh_network
#+end_src

** Setting environment variables

The project includes an =.env.example= file with information regarding the
available environment variables.  Make a copy of the file, rename it to =.env=,
and fill/modify any necessary values.

** Launching Wazuh

After initialization, all components can be deployed through the top level
=docker-compose.yaml= file.

#+CALL: docker-compose-run()

#+CALL: docker-compose-kill()

* COMMENT Code blocks

** Variables

#+NAME: current-directory
#+begin_src emacs-lisp
  default-directory
#+end_src

#+NAME: wazuh-agent-directory
#+begin_src emacs-lisp :cache yes
  (concat default-directory "agent/")
#+end_src

#+NAME: wazuh-server-directory
#+begin_src emacs-lisp :cache yes
  (concat default-directory "server/")
#+end_src

** Project deployment

#+NAME: docker-compose-run
#+begin_src sh :var dir=current-directory() :var file="docker-compose.yaml" :results verbatim
  cd $dir

  docker compose -f $file up --build -d 2>&1
#+end_src

#+NAME: docker-compose-kill
#+begin_src sh :var dir=current-directory() :var file="docker-compose.yaml" :results verbatim
  cd $dir

  docker compose -f $file down --remove-orphans 2>&1
#+end_src

** Manager reconfiguration

[[wazuh-server-remove-config-directory][wazuh-server-remove-config-directory()]]

#+CALL: wazuh-server-generate-certificates()

#+CALL: wazuh-server-run-vanilla()

#+CALL: wazuh-server-kill-vanilla()

[[wazuh-server-update-configuration-files][wazuh-server-update-configuration-files()]]
