#!/usr/bin/env python3
import sys
import asyncio
import nats
import json
import datetime
import os

#Custom Integration Script triggered by SIEM. It publishes the whole alert via NATS and
#Engine subscribes to it in order to receive it.

NATS_BROKER = 'nats://172.26.0.1:4222' #NATS Broker
NATS_SUBJECT = "alerts" #Alerts topic

async def main():
    inicio = datetime.datetime.now()
    # Read alert log file
    alert_file = open(sys.argv[1])

    # Get alert as JSON
    alert_json = json.loads(alert_file.read())
    alert_file.close()

    #Convert JSON into a String
    alert_json_string = json.dumps(alert_json)

    #Publish alert log in topic 'alerts' of NATS broker
    nc = await nats.connect(servers=[NATS_BROKER])
    await nc.publish(NATS_SUBJECT, bytes(alert_json_string, 'utf-8'))
    await nc.flush()
    await nc.close()

    fin = datetime.datetime.now()
    tiempo = fin - inicio
    os.system(f"echo {tiempo} > tiempo.txt")

if __name__ == '__main__':
    asyncio.run(main())
